server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/user_service_db
    username: user_service_user
    password: user_service_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: ""
    sql-migration-separator: "_"
    sql-migration-suffixes: .sql
    out-of-order: false

security:
  jwt:
    secret: "very-secret-key-very-secret-key-1234567890"
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always